# Generated by Django 4.0.4 on 2022-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
