# Generated by Django 4.0.4 on 2022-05-12 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator_app', '0002_formentry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
