# Generated by Django 4.0.4 on 2022-05-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator_app', '0003_formentry_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormFieldEntry',
        ),
    ]
